server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.18.1.20:3306/user?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: admink
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: MoneySaveApplication